services:
  api:
    build: .
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://postgres:postgres@db:5432/emotrack}
      LOG_LEVEL: INFO
      STATIC_DIR: ${STATIC_DIR:-}
    volumes:
      - ./:/app
    depends_on:
      - redis
      - db
    restart: unless-stopped

  worker:
    build: .
    command: celery -A backend.app.celery_app.celery_app worker -l info
    environment:
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://postgres:postgres@db:5432/emotrack}
      LOG_LEVEL: INFO
    volumes:
      - ./:/app
    depends_on:
      - redis
    restart: unless-stopped

  seed:
    build: .
    command: python -m backend.seed_data --reset --yes
    environment:
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://postgres:postgres@db:5432/emotrack}
      LOG_LEVEL: INFO
      ENABLE_ENCRYPTION: ${ENABLE_ENCRYPTION:-0}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-}
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    restart: "no"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=emotrack
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
